# Use postgres/example user/password credentials
version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  centos:
    build:
      context: ./ingestion
      dockerfile: Dockerfile  # Make sure this points to the correct Dockerfile in the context
    image: centos
    networks:
      - postgres
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python /app/src/get_apis_data.py'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_NAME=${POSTGRES_SERVICE_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - SCHOOLS_TABLE_NAME=${SCHOOLS_TABLE_NAME}
      - CITIES_TABLE_NAME=${CITIES_TABLE_NAME}
      - POSTGRES_DEFAULT_SCHEMA=${POSTGRES_DEFAULT_SCHEMA}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SCHOOLS_ENDPOINT=${SCHOOLS_ENDPOINT}
      - SCHOOLS_API_KEY=${SCHOOLS_API_KEY}
      - CITIES_API_ENDPOINT=${CITIES_API_ENDPOINT}
      - CITIES_API_KEY=${CITIES_API_KEY}
networks:
  postgres:
    driver: bridge