CREATE TABLE IF NOT EXISTS SCHOOLS(
    ID TEXT PRIMARY KEY,
    NAME TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIP TEXT,
    URL TEXT,
    OWNERSHIP TEXT,
    MAIN_CAMPUS TEXT,
    ONLINE_ONLY TEXT,
    OPEN_ADMISSIONS_POLICY TEXT,
    DEGREES_AWARDED_PREDOMINANT NUMERIC(38,2),
    DEGREES_AWARDED_PREDOMINANT_RECODED NUMERIC(38,2)
);

CREATE TABLE IF NOT EXISTS CITYS(
    NAME TEXT PRIMARY KEY,
    LATITUDE TEXT,
    LONGITUDE TEXT,
    COUNTRY TEXT,
    POPULATION NUMERIC(38,2),
    IS_CAPITAL BOOLEAN,
    MAIN_CAMPUS TEXT,
    ONLINE_ONLY TEXT
);